name: Build and Package PyQt6 Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playsound==1.2.2 PyQt6-Fluent-Widgets==1.6.2 PyQt6>=6.7.1
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller main.spec

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: exe-file
          path: dist/ClassManager.exe
