name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playsound==1.2.2 PyQt6-Fluent-Widgets==1.6.2 PyQt6>=6.7.1
        pip install pyinstaller

    - name: List directories
      run: |
        echo "Listing audio directory:"
        ls -R audio || echo "audio directory not found"
        echo "Listing config directory:"
        ls -R config || echo "config directory not found"
        echo "Listing img directory:"
        ls -R img || echo "img directory not found"
        echo "Listing ui directory:"
        ls -R ui || echo "ui directory not found"

    - name: Build with PyInstaller
      run: |
        pyinstaller main.spec || { echo 'PyInstaller build failed'; exit 1; }

    - name: Compress build output
      run: |
        zip -r build-output.zip dist || { echo 'Failed to zip build output'; exit 1; }

    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build-output.zip
